---
- name: Create danger directory
  ansible.builtin.file:
    path: "{{ danger_work_dir }}"
    state: directory
    mode: '0755'
- name: install klipper stuff
  shell: |
      distrobox enter --root {{default_image_name}} -- sudo apt-get update && sudo apt-get install git systemctl -y

