---
- name: Create searxng work directory
  ansible.builtin.file:
    path: ~/searxng/
    state: directory
    mode: '0755'
- name: stop container
  shell: |
      docker-compose stop
  args:
      chdir: ~/searxng/
  ignore_errors: yes
- name: stop container
  shell: |
      docker-compose rm -f
  args:
      chdir: ~/searxng/
  ignore_errors: yes
- name: copy compose file to searxng/compose
  template:
    src: compose.yaml.j2
    dest: "~/searxng/compose.yaml"
- name: start container
  shell: |
      docker-compose up -d
  args:
     chdir: ~/searxng/