---
- name: stop container
  shell: |
      docker compose stop
  args:
      chdir: ~/minio/
  ignore_errors: yes
- name: remove container
  shell: |
      docker compose rm -y
  args:
     chdir: ~/minio/
  ignore_errors: yes
- name: install mc
  shell: |
      curl https://dl.min.io/client/mc/release/linux-amd64/mc --create-dirs -o $HOME/minio-binaries/mc
      chmod +x $HOME/minio-binaries/mc
      export PATH=$PATH:$HOME/minio-binaries/
  args:
     chdir: ~/minio/
  ignore_errors: yes
- name: Ensure group miniproc exists with set gid
  ansible.builtin.group:
    name: minio
    state: present
    gid: 473
  become: yes
- name: Ensure miniproc user exists with set uid & gid
  ansible.builtin.user:
    name: minio
    comment: minio
    uid: 473
    group: 473
  become: yes
- name: setup ownership
  shell: |
      chown -R miniproc:miniproc /mnt/drobo/minio
  ignore_errors: yes
  become: yes
- name: Create minio directory
  ansible.builtin.file:
    path: ~/minio/
    state: directory
    mode: '0755'
- name: copy compose file to minio/compose
  template:
    src: compose.yaml
    dest: "~/minio/compose.yaml"
- name: start container
  shell: |
      docker compose up -d --remove-orphans
  args:
     chdir: ~/minio/
#- name: initialize buckets
#  shell: |
##    ~/minio-binaries/mc config host add harvard-minio http://localhost:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
##    ~/minio-binaries/mc mb harvard-minio/test-2
##    ~/minio-binaries/mc policy download harvard-minio/test-2
##    ~/minio-binaries/mc cp /mnt/drobo/A/video/Movies/ harvard-minio/test-2 --recursive
