---

caddy_tls_providers:
  - provider: cloudflare
    challenge_type: dns
    provider_api_token: "{{ cloudflare_api_token }}"
    resolver_ip: 1.1.1.1

caddy_endpoints:
  - friendly_name: jf
    fqdn: jellyfin.xoxd.me
    upstream: "harvard-music:2285"
    tls_insecure: false
    tls_provider: cloudflare
  - friendly_name: search
    fqdn: search.hewow.gay
    upstream: "harvard-music:8080"
    tls_insecure: false
    tls_provider: cloudflare
