---
- name: stop container
  shell: |
    wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
    wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources
    apt-get update
    apt install pipewire-audio-client-libraries -y
    dnf install --nogpgcheck https://dl.fedoraproject.org/pub/epel/epel-release-latest-$(rpm -E %rhel).noarch.rpm
    dnf install --nogpgcheck https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-$(rpm -E %rhel).noarch.rpm https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-$(rpm -E %rhel).noarch.rpm
    dnf install distrobox -y                                                                                                                                                                                                  
  become: yes
- name: Create jellyfin directory
  ansible.builtin.file:
    path: ~/jellyfin/
    state: directory
    mode: '0755'
- name: copy compose file to jellyfin/compose
  template:
    src: compose.yaml
    dest: "~/jellyfin/compose.yaml"
- name: start container
  shell: |
      docker-compose up -d
  args:
     chdir: ~/jellyfin/
