services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - /mnt/appdata/mediaservers/jellyfin:/config
      - /mnt/drobo:/A
      - /home/jess/s3:/s3
    ports:
      - 2285:8096
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - JELLYFIN_PublishedServerUrl=jellyfin.xoxd.me
    hostname: us-rdu
    restart: unless-stopped