---
- name: Create minio direct directory
  ansible.builtin.file:
    path: ~/minio-linux/
    state: directory
    mode: '0755'
- name: fetch and install minio rpm
  shell: |
    wget https://dl.min.io/server/minio/release/linux-amd64/archive/minio-20241107005220.0.0-1.x86_64.rpm -O minio.rpm
    dnf -y install minio.rpm
  args:
     chdir: /home/{{uname}}/minio-linux/
  become: yes
- name: setup minio users and stuff
  shell: |
    groupadd -r minio-user
    useradd -M -r -g minio-user minio-user
    chown minio-user:minio-user /mnt/drobo
  become: yes
  args:
     chdir: /home/{{uname}}/minio-linux/
- name: copy service file into place
  template:
    src: minio.service.j2
    dest: "/usr/lib/systemd/system/minio.service"
  args:
     chdir: /home/{{uname}}/minio-linux/
  become: yes
- name: copy env file into place
  template:
    src: minio.j2
    dest: "/etc/default/minio"
  args:
     chdir: /home/{{uname}}/minio-linux/
  become: yes
- name: fetch and add kes binary
  shell: |
    wget https://github.com/minio/kes/releases/latest/download/kes-linux-amd64 -O kes
    chmod +x kes
    export PATH=$PATH:@HOME/minio-linux/kes
  args:
     chdir: /home/{{uname}}/minio-linux/kes
  become: yes
- name: fetch and add kes binary
  shell: |
    minio-linux/kes identity new --ip "127.0.0.1" --key "private.key" --cert "public.crt" localhost
    minio-linux/kes identity new --key=client.key --cert=client.crt HarvardMinio
    setcap cap_ipc_lock=+ep $(readlink -f $(which kes))

  args:
     chdir: /home/{{uname}}/minio-linux/kes
  become: yes
